"use client";

import MatchScore from "./MatchScore";
import ResourceActions from "./ResourceActions";

type Resource = {
  id: string;
  name?: string;
  category?: string;
  city?: string;
  province?: string;
  address?: string;
  description?: string;
  eligibility?: string;
  languages?: string | string[];
  services?: string | string[];
  tags?: string | string[];
  transportation?: string | string[];
  phone?: string;
  website?: string;
  verified?: boolean | string;
  matchScore?: number;
  matchReasons?: string[];
  district?: string;
  region?: string;
  coverageArea?: string | string[];
};

type Analysis = {
  userType?: string;
  location?: string;
  transportation?: string;
  urgency?: string;
  needs?: string[];
  detectedLanguage?: string;
  languages?: string[];
};

type Props = {
  resource: Resource;
  analysis?: Analysis;
};

function toArray(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map(String).filter(Boolean);
  }

  if (typeof value === "string") {
    const trimmed = value.trim();

    if (!trimmed) return [];

    if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
      try {
        const parsed = JSON.parse(trimmed);

        if (Array.isArray(parsed)) {
          return parsed.map(String).filter(Boolean);
        }
      } catch {
        // Fall through to comma-separated parsing.
      }
    }

    return trimmed
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }

  return [];
}

function getCategoryIcon(category?: string) {
  const value = category?.toLowerCase() || "";

  if (
    value.includes("food") ||
    value.includes("grocer") ||
    value.includes("nutrition")
  ) {
    return "🍎";
  }

  if (
    value.includes("employment") ||
    value.includes("job") ||
    value.includes("career")
  ) {
    return "💼";
  }

  if (
    value.includes("newcomer") ||
    value.includes("settlement") ||
    value.includes("immigrant")
  ) {
    return "🌎";
  }

  if (
    value.includes("language") ||
    value.includes("education")
  ) {
    return "📚";
  }

  if (
    value.includes("housing") ||
    value.includes("shelter")
  ) {
    return "🏠";
  }

  if (
    value.includes("health") ||
    value.includes("medical")
  ) {
    return "🏥";
  }

  if (
    value.includes("transportation") ||
    value.includes("transit") ||
    value.includes("mobility")
  ) {
    return "🚌";
  }

  return "🤝";
}

function getDirectionsUrl(resource: Resource) {
  const address =
    resource.address ||
    [resource.city, resource.province]
      .filter(Boolean)
      .join(", ");

  if (!address) return "#";

  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    address
  )}`;
}

function getWhyMatched(
  resource: Resource,
  analysis?: Analysis
): string[] {
  const backendReasons = Array.isArray(
    resource.matchReasons
  )
    ? resource.matchReasons
        .map((reason) => String(reason).trim())
        .filter(Boolean)
    : [];

  /*
   * Prefer the reasons generated by the backend scoring engine.
   *
   * These reasons are based on the same scoring logic that
   * determines the resource's match score.
   */
  if (backendReasons.length > 0) {
    return backendReasons.slice(0, 5);
  }

  /*
   * Fallback for older resources / responses that do not
   * contain matchReasons.
   */
  const fallbackReasons: string[] = [];

  if (analysis?.location && resource.city) {
    const requestedLocation =
      analysis.location.toLowerCase();

    const resourceCity =
      resource.city.toLowerCase();

    if (
      resourceCity.includes(requestedLocation) ||
      requestedLocation.includes(resourceCity)
    ) {
      fallbackReasons.push(
        `Located in ${analysis.location}`
      );
    }
  }

  if (
    analysis?.needs &&
    analysis.needs.length > 0
  ) {
    const services = toArray(
      resource.services
    ).map((item) => item.toLowerCase());

    const matchingNeed =
      analysis.needs.find((need) =>
        services.some(
          (service) =>
            service.includes(
              need.toLowerCase()
            ) ||
            need
              .toLowerCase()
              .includes(service)
        )
      );

    if (matchingNeed) {
      fallbackReasons.push(
        `Supports ${matchingNeed}`
      );
    }
  }

  if (
    analysis?.transportation &&
    analysis.transportation !== "Unknown"
  ) {
    const transportation =
      toArray(
        resource.transportation
      );

    if (transportation.length > 0) {
      fallbackReasons.push(
        "Transportation information available"
      );
    }
  }

  if (
    resource.languages &&
    toArray(resource.languages).length > 0
  ) {
    fallbackReasons.push(
      "Language support available"
    );
  }

  if (fallbackReasons.length === 0) {
    fallbackReasons.push(
      "Relevant community support"
    );
  }

  return fallbackReasons.slice(0, 5);
}

function getScoreLabel(score: number) {
  if (score >= 90) return "Excellent match";
  if (score >= 75) return "Strong match";
  if (score >= 60) return "Good match";
  if (score >= 40) return "Relevant match";
  return "Potential match";
}

export default function ResourceCard({
  resource,
  analysis,
}: Props) {
  const services = toArray(resource.services);
  const languages = toArray(resource.languages);
  const transportation = toArray(
    resource.transportation
  );

  const score =
    typeof resource.matchScore === "number"
      ? Math.max(0, Math.min(100, resource.matchScore))
      : 0;

  const reasons = getWhyMatched(
    resource,
    analysis
  );

  const verified =
    resource.verified === true ||
    String(resource.verified).toLowerCase() ===
      "true";

  const location =
    resource.address ||
    [resource.city, resource.province]
      .filter(Boolean)
      .join(", ");

  return (
    <article
      aria-label={`${resource.name || "Community Resource"} resource`}
      className="
        group relative overflow-hidden
        rounded-[1.75rem]
        border border-white/80
        bg-white/85
        shadow-[0_18px_55px_rgba(15,23,42,0.09)]
        backdrop-blur-xl
        transition-all duration-300
        hover:-translate-y-1
        hover:border-blue-200
        hover:shadow-[0_30px_80px_rgba(30,64,175,0.18)]
        motion-reduce:transform-none
        motion-reduce:transition-none
      "
    >
      {/* Decorative lighting */}
      <div
        aria-hidden="true"
        className="
          pointer-events-none absolute
          -right-20 -top-20
          h-44 w-44
          rounded-full
          bg-blue-300/20
          blur-3xl
          transition-transform duration-700
          group-hover:scale-150
          motion-reduce:transition-none
        "
      />

      <div
        aria-hidden="true"
        className="
          pointer-events-none absolute
          -bottom-24 -left-24
          h-48 w-48
          rounded-full
          bg-indigo-300/10
          blur-3xl
        "
      />

      <div className="relative p-5 sm:p-6">
        {/* Header */}
        <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex min-w-0 gap-4">
            {/* Category icon */}
            <div
              aria-hidden="true"
              className="
                flex h-14 w-14 shrink-0
                items-center justify-center
                rounded-2xl
                bg-gradient-to-br
                from-blue-600
                via-indigo-600
                to-violet-600
                text-2xl
                shadow-lg
                shadow-blue-900/20
                transition-transform duration-300
                group-hover:scale-105
                group-hover:rotate-1
                motion-reduce:transform-none
                motion-reduce:transition-none
              "
            >
              {getCategoryIcon(resource.category)}
            </div>

            {/* Title and metadata */}
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <h3 className="break-words text-lg font-black leading-tight text-slate-950 sm:text-xl">
                  {resource.name || "Community Resource"}
                </h3>

                {verified && (
                  <span
                    className="
                      inline-flex shrink-0
                      items-center gap-1.5
                      rounded-full
                      border border-emerald-200
                      bg-emerald-50
                      px-2.5 py-1
                      text-xs font-bold
                      text-emerald-800
                    "
                    title="This resource is verified"
                  >
                    <span
                      aria-hidden="true"
                      className="
                        flex h-4 w-4
                        items-center justify-center
                        rounded-full
                        bg-emerald-600
                        text-[10px]
                        font-black
                        text-white
                      "
                    >
                      ✓
                    </span>
                    Verified
                  </span>
                )}
              </div>

              {resource.category && (
                <p className="mt-1 text-sm font-bold text-blue-700">
                  {resource.category}
                </p>
              )}

              {location && (
                <div className="mt-2 flex items-start gap-2 text-sm text-slate-600">
                  <span
                    aria-hidden="true"
                    className="mt-0.5"
                  >
                    📍
                  </span>

                  <span className="leading-5">
                    {location}
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* Match score */}
          <div className="flex shrink-0 items-center gap-3 sm:flex-col sm:items-end">
            <MatchScore score={score} />

            <span className="text-xs font-bold text-slate-500 sm:hidden">
              {getScoreLabel(score)}
            </span>
          </div>
        </div>

        {/* Desktop score explanation */}
        <div
          className="
            mt-4 hidden
            items-center justify-end
            gap-2
            sm:flex
          "
        >
          <span className="text-xs font-semibold text-slate-500">
            {getScoreLabel(score)}
          </span>

          <span
            aria-hidden="true"
            className="h-1.5 w-1.5 rounded-full bg-blue-400"
          />

          <span className="text-xs font-medium text-slate-500">
            Matched using your needs and preferences
          </span>
        </div>

        {/* Description */}
        {resource.description && (
          <p className="mt-5 text-sm leading-6 text-slate-600">
            {resource.description}
          </p>
        )}

        {/* Why this matches */}
        {reasons.length > 0 && (
          <section
            aria-labelledby={`match-reasons-${resource.id}`}
            className="
              mt-5 rounded-2xl
              border border-blue-100
              bg-gradient-to-br
              from-blue-50/90
              to-indigo-50/60
              p-4
            "
          >
            <div className="flex items-center gap-2">
              <span
                aria-hidden="true"
                className="
                  flex h-7 w-7
                  items-center justify-center
                  rounded-lg
                  bg-blue-600
                  text-sm
                  text-white
                  shadow-sm
                "
              >
                ✓
              </span>

              <h4
                id={`match-reasons-${resource.id}`}
                className="text-sm font-extrabold text-blue-950"
              >
                Why this is a good match
              </h4>
            </div>

            <ul className="mt-3 space-y-2">
              {reasons.map((reason) => (
                <li
                  key={reason}
                  className="flex items-start gap-2 text-sm leading-5 text-blue-950"
                >
                  <span
                    aria-hidden="true"
                    className="mt-0.5 font-bold text-blue-600"
                  >
                    ✓
                  </span>

                  <span>{reason}</span>
                </li>
              ))}
              {analysis && (
  <div className="mt-4 border-t border-blue-100 pt-3">
    <p className="text-xs font-bold uppercase tracking-wider text-blue-700">
      Based on your request
    </p>

    <div className="mt-2 flex flex-wrap gap-2">
      {analysis.location && (
        <span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-700 shadow-sm">
          📍 {analysis.location}
        </span>
      )}

      {analysis.needs
        ?.slice(0, 2)
        .map((need) => (
          <span
            key={need}
            className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-700 shadow-sm"
          >
            {need}
          </span>
        ))}

      {analysis.transportation &&
        analysis.transportation !==
          "Unknown" && (
          <span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-700 shadow-sm">
            🚌 {analysis.transportation}
          </span>
        )}

      {analysis.detectedLanguage && (
        <span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-700 shadow-sm">
          🌐 {analysis.detectedLanguage}
        </span>
      )}
    </div>
  </div>
)}
            </ul>
          </section>
        )}

        {/* Primary services */}
        {services.length > 0 && (
          <section
            aria-labelledby={`services-${resource.id}`}
            className="mt-5"
          >
            <h4
              id={`services-${resource.id}`}
              className="
                mb-2.5
                text-xs font-extrabold
                uppercase tracking-wider
                text-slate-500
              "
            >
              Services
            </h4>

            <div className="flex flex-wrap gap-2">
              {services.slice(0, 6).map((service) => (
                <span
                  key={service}
                  className="
                    rounded-full
                    border border-slate-200
                    bg-slate-50
                    px-3 py-1.5
                    text-xs font-semibold
                    text-slate-700
                    transition-colors
                    group-hover:border-blue-100
                    group-hover:bg-blue-50
                  "
                >
                  {service}
                </span>
              ))}

              {services.length > 6 && (
                <span
                  className="
                    rounded-full
                    border border-blue-100
                    bg-blue-50
                    px-3 py-1.5
                    text-xs font-bold
                    text-blue-700
                  "
                >
                  +{services.length - 6} more
                </span>
              )}
            </div>
          </section>
        )}

        {/* Expandable details */}
        {(languages.length > 0 ||
          transportation.length > 0 ||
          resource.eligibility ||
          resource.tags) && (
          <details
            className="
              group/details mt-5
              rounded-2xl
              border border-slate-200
              bg-slate-50/70
              open:bg-white
            "
          >
            <summary
              className="
                flex cursor-pointer
                list-none items-center
                justify-between
                gap-4
                rounded-2xl
                px-4 py-3.5
                text-sm font-bold
                text-slate-800
                outline-none
                transition-colors
                hover:bg-slate-100
                focus-visible:ring-3
                focus-visible:ring-blue-600
                focus-visible:ring-offset-2
                [&::-webkit-details-marker]:hidden
                motion-reduce:transition-none
              "
            >
              <span className="flex items-center gap-2">
                <span aria-hidden="true">ℹ️</span>
                More resource details
              </span>

              <span
                aria-hidden="true"
                className="
                  text-lg text-slate-400
                  transition-transform duration-200
                  group-open/details:rotate-180
                  motion-reduce:transition-none
                "
              >
                ↓
              </span>
            </summary>

            <div className="grid gap-3 px-4 pb-4 sm:grid-cols-2">
              {languages.length > 0 && (
                <div className="rounded-xl border border-slate-200 bg-white p-4">
                  <p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">
                    Languages
                  </p>

                  <p className="mt-2 text-sm leading-5 text-slate-700">
                    {languages.slice(0, 8).join(", ")}
                  </p>
                </div>
              )}

              {transportation.length > 0 && (
                <div className="rounded-xl border border-slate-200 bg-white p-4">
                  <p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">
                    Transportation
                  </p>

                  <p className="mt-2 text-sm leading-5 text-slate-700">
                    {transportation.slice(0, 8).join(", ")}
                  </p>
                </div>
              )}

              {resource.eligibility && (
                <div className="rounded-xl border border-slate-200 bg-white p-4 sm:col-span-2">
                  <p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">
                    Eligibility
                  </p>

                  <p className="mt-2 text-sm leading-5 text-slate-700">
                    {resource.eligibility}
                  </p>
                </div>
              )}

              {toArray(resource.tags).length > 0 && (
                <div className="rounded-xl border border-slate-200 bg-white p-4 sm:col-span-2">
                  <p className="text-xs font-extrabold uppercase tracking-wider text-slate-500">
                    Related topics
                  </p>

                  <div className="mt-2 flex flex-wrap gap-2">
                    {toArray(resource.tags)
                      .slice(0, 10)
                      .map((tag) => (
                        <span
                          key={tag}
                          className="
                            rounded-full
                            bg-slate-100
                            px-2.5 py-1
                            text-xs font-medium
                            text-slate-600
                          "
                        >
                          {tag}
                        </span>
                      ))}
                  </div>
                </div>
              )}
            </div>
          </details>
        )}

        {/* Actions */}
        <div className="mt-6 border-t border-slate-200 pt-5">
          <ResourceActions
            resource={resource}
            directionsUrl={getDirectionsUrl(resource)}
            requestedLocation={analysis?.location}
          />
        </div>
      </div>
    </article>
  );
}
